import { MD3LightTheme, MD3DarkTheme, configureFonts } from 'react-native-paper';

import { colors } from './colors';
import { typography } from './typography';

import type { MD3Theme, MD3TypescaleKey } from 'react-native-paper';

const fontConfig: Partial<Record<MD3TypescaleKey, { fontFamily: string }>> = {
  displayLarge: { fontFamily: typography.fontFamily.sans },
  displayMedium: { fontFamily: typography.fontFamily.sans },
  displaySmall: { fontFamily: typography.fontFamily.sans },
  headlineLarge: { fontFamily: typography.fontFamily.sans },
  headlineMedium: { fontFamily: typography.fontFamily.sans },
  headlineSmall: { fontFamily: typography.fontFamily.sans },
  titleLarge: { fontFamily: typography.fontFamily.sans },
  titleMedium: { fontFamily: typography.fontFamily.sans },
  titleSmall: { fontFamily: typography.fontFamily.sans },
  labelLarge: { fontFamily: typography.fontFamily.sans },
  labelMedium: { fontFamily: typography.fontFamily.sans },
  labelSmall: { fontFamily: typography.fontFamily.sans },
  bodyLarge: { fontFamily: typography.fontFamily.sans },
  bodyMedium: { fontFamily: typography.fontFamily.sans },
  bodySmall: { fontFamily: typography.fontFamily.sans },
};

export const lightTheme: MD3Theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: colors.primary.DEFAULT,
    primaryContainer: colors.primary[100],
    onPrimary: colors.text.inverse,
    onPrimaryContainer: colors.primary[900],
    secondary: colors.nequi.purple,
    secondaryContainer: '#F3E8FF',
    onSecondary: colors.text.inverse,
    onSecondaryContainer: colors.nequi.purple,
    tertiary: colors.bbva.blue,
    tertiaryContainer: '#E0F2FE',
    onTertiary: colors.text.inverse,
    onTertiaryContainer: colors.bbva.navy,
    error: colors.semantic.error,
    errorContainer: '#FEE2E2',
    onError: colors.text.inverse,
    onErrorContainer: '#991B1B',
    background: colors.background.primary,
    onBackground: colors.text.primary,
    surface: colors.surface.card,
    onSurface: colors.text.primary,
    surfaceVariant: colors.background.secondary,
    onSurfaceVariant: colors.text.secondary,
    outline: '#D1D5DB',
    outlineVariant: '#E5E7EB',
    shadow: '#000000',
    scrim: 'rgba(0, 0, 0, 0.5)',
    inverseSurface: colors.text.primary,
    inverseOnSurface: colors.text.inverse,
    inversePrimary: colors.primary[300],
    elevation: {
      level0: 'transparent',
      level1: colors.surface.card,
      level2: colors.surface.card,
      level3: colors.surface.elevated,
      level4: colors.surface.elevated,
      level5: colors.surface.elevated,
    },
    surfaceDisabled: 'rgba(26, 26, 26, 0.12)',
    onSurfaceDisabled: 'rgba(26, 26, 26, 0.38)',
    backdrop: colors.surface.overlay,
  },
  fonts: configureFonts({ config: fontConfig }),
};

export const darkTheme: MD3Theme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: colors.primary[400],
    primaryContainer: colors.primary[800],
    onPrimary: colors.primary[900],
    onPrimaryContainer: colors.primary[100],
    secondary: colors.nequi.pink,
    secondaryContainer: '#4A1D6A',
    onSecondary: '#2D0A47',
    onSecondaryContainer: '#F3E8FF',
    tertiary: colors.bbva.aqua,
    tertiaryContainer: '#003A5C',
    onTertiary: '#00293F',
    onTertiaryContainer: '#E0F2FE',
    error: '#F87171',
    errorContainer: '#7F1D1D',
    onError: '#450A0A',
    onErrorContainer: '#FEE2E2',
    background: '#121212',
    onBackground: '#E5E5E5',
    surface: '#1E1E1E',
    onSurface: '#E5E5E5',
    surfaceVariant: '#2D2D2D',
    onSurfaceVariant: '#A3A3A3',
    outline: '#525252',
    outlineVariant: '#404040',
    shadow: '#000000',
    scrim: 'rgba(0, 0, 0, 0.7)',
    inverseSurface: '#E5E5E5',
    inverseOnSurface: '#1A1A1A',
    inversePrimary: colors.primary[700],
    elevation: {
      level0: 'transparent',
      level1: '#1E1E1E',
      level2: '#232323',
      level3: '#282828',
      level4: '#2D2D2D',
      level5: '#323232',
    },
    surfaceDisabled: 'rgba(229, 229, 229, 0.12)',
    onSurfaceDisabled: 'rgba(229, 229, 229, 0.38)',
    backdrop: 'rgba(0, 0, 0, 0.7)',
  },
  fonts: configureFonts({ config: fontConfig }),
};

export type AppTheme = typeof lightTheme;
